#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : PyWavelets
Version  : 0.5.2
Release  : 3
URL      : https://pypi.python.org/packages/4b/df/3fff2a8b96ef7df6e4e8642fb7569c3717ae562dd76afe0f96525c0af784/PyWavelets-0.5.2.tar.gz
Source0  : https://pypi.python.org/packages/4b/df/3fff2a8b96ef7df6e4e8642fb7569c3717ae562dd76afe0f96525c0af784/PyWavelets-0.5.2.tar.gz
Summary  : PyWavelets, wavelet transform module
Group    : Development/Tools
License  : MIT
Requires: PyWavelets-python
Requires: Cython
Requires: nose
Requires: numpy
Requires: wheel
BuildRequires : numpy
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools

%description
PyWavelets
==========
.. contents::
What is PyWavelets
------------------
PyWavelets is a free Open Source library for wavelet transforms in Python.
Wavelets are mathematical basis functions that are localized in both time and
frequency.  Wavelet transforms are time-frequency transforms employing
wavelets.  They are similar to Fourier transforms, the difference being that
Fourier transforms are localized only in frequency instead of in time and
frequency.

%package python
Summary: python components for the PyWavelets package.
Group: Default
Provides: pywavelets-python

%description python
python components for the PyWavelets package.


%prep
%setup -q -n PyWavelets-0.5.2

%build
export LANG=C
export SOURCE_DATE_EPOCH=1490905652
python3 setup.py build -b py3

%install
rm -rf %{buildroot}
python3 -tt setup.py build -b py3 install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)
/usr/lib/python3*/*
